
{% set data = load_setup_py_data() %}

package:
    name: corrct
    
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: {{ data['url'] }}
    license_file: LICENSE.md
    summary: {{ data['description'] }}

extra:
    maintainers:
        - Nicola VIGANO
