{%- set pyproject = load_file_data('pyproject.toml') %}
{%- set project = pyproject.get('project', {}) %}
{%- set py_min_version = project['requires-python'] %}
{%- set py_build_version = py_min_version | replace('>', '') | replace('=', '') %}

package:
    name: {{ project['name'] }}
    version: {{ project['version'] }}

source:
    path: ../

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed . -vv

requirements:
    host:
        - python {{ py_build_version }}.*
        - pip

    run:
        - python {{ py_min_version }}
        # dependencies are defined in setup.py
        {% for dep in project['dependencies'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: {{ project['urls']['Homepage'] }}
    license: {{ project['license'] }}
    summary: {{ project['description'] }}
    doc_url: {{ project['urls']['Documentation'] }}

extra:
    maintainers:
        - Nicola VIGANO
